/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AtDwivedi' at '10/5/16 11:06 AM' with Gradle 2.14.1
 *
 * @author AtDwivedi, @date 10/5/16 11:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
